### ISSUE TITLE
name to fetch should be a string

### ISSUE THREAD

**Issue by benoitc** [barrel-db/rebar3_elixir#1]
the `Name` in `{elixir, Name, Vsn}` should be a string. Right now an atom is expected.

**Comment by sivsushruth** [comment]
Fixed via https://github.com/barrel-db/rebar3_elixir/commit/0ca59135c68e204dc843d10bea3bfa1f1ec39c1c

**Comment by sivsushruth** [comment]
Closing via https://github.com/barrel-db/rebar3_elixir/commit/0ca59135c68e204dc843d10bea3bfa1f1ec39c1c
