### ISSUE TITLE
Tag commit c2a8c9

### ISSUE THREAD

**Issue by eseres** [barrel-db/rebar3_elixir#40]
Could you please tag commit ref c2a8c9fe95b1ecb12c9fc174dfc46da5208f0e96?
Thank you.

**Comment by eseres** [comment]
Not needed anymore, I will just use the git ref in rebar.config.

**Comment by benoitc** [comment]
?

**Comment by eseres** [comment]
MongoDB driver (https://hex.pm/packages/mongodb) will not build with HEAD of master of rebar3_elixir_compile. And I did not realize that I could provide a git ref in the rebar.config pulling rebar3_elixir_compile in as a plugin. Now I do and did so. 

Also, I'd given you the wrong git ref which I thought was the HEAD of master that I had been using. The one I'd been using and which I'm going to lock to now is, 75a84d.

Thanks for responding.
