### ISSUE TITLE
rebar3_elixir_util.erl:get_details/1 should use rebar API

### ISSUE THREAD

**Issue by benoitc** [barrel-db/rebar3_elixir#5]
Right now `rebar3_elixir_util.erl:get_details/1` is opening rebar.config.

Instead we should use the [rebar API](http://www.rebar3.org/docs/plugins#section-rebar-api) to get the elixir options so can also have the global options set too.

**Comment by benoitc** [comment]
related to #4

**Comment by sivsushruth** [comment]
closing via https://github.com/barrel-db/rebar3_elixir/commit/35c36530494a4d77b49e0e3306e694fb9a382eb3
