### ISSUE TITLE
discover apps from deps

### ISSUE THREAD

**Issue by benoitc** [barrel-db/rebar3_elixir#6]
Right now it seems that the elixir applications are discovered from a static folder:
https://github.com/barrel-db/rebar3_elixir/blob/master/src/rebar3_elixir_util.erl#L29

Instead we should use applications listed in deps and check if `mix.exs` is present and then compile it using mix until `rebar.config` is not present. Thoughts?

**Comment by sivsushruth** [comment]
Checks for mix.exs, if present uses mix to compile
